# Matrices and operations on them

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [ ]:
import numpy as np

## 1. Creating matrix

In [3]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print ("Маtrix:\n", a)

Маtrix:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


The second way to create - using the built-in functions __`numpy.eye (N, M = None, ...)` __, __`numpy.zeros (shape, ...) `__, __`numpy.ones (shape , ...) `__.

### Identity Matrix
- Square matrix
- Ones on the main diagonal
- Zeros everywhere else
- Denoted by I. If a subscript is included, it is the order of the identity matrix.
- I is the multiplicative identity for matrices
- Any matrix times the identity matrix is the original matrix.
- Multiplication by the identity matrix is commutative, although the order of the identity may change

In [5]:
b = np.eye(5)
print ("Identity matrix:\n", b)

Identity matrix:
 [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [6]:
c = np.ones((7, 5))
print ("A matrix consisting of only one:\n", c)

A matrix consisting of only one:
 [[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


__ Note: the dimension of the array is specified not by two function arguments, but by one - a tuple! __ \ n 

In [12]:
v = np.arange(0, 24, 2)
print ("row matrix:\n", v,np.shape(v))
d = v.reshape((3, 4))
print ("Matrix:\n", d,"\nMatrix size:",np.shape(d))

row matrix:
 [ 0  2  4  6  8 10 12 14 16 18 20 22] (12,)
Matrix:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 
Matrix size: (3, 4)


## 2. Matrix Operations

### 1. Matrix Addition


In [8]:
# Define two arrays
A = np.array([[1, 0  ], [2, 5], [3, 1]])
B = np.array([[4, 0.5], [2, 5], [0, 1]])

# Add them together
print(A+B)

[[ 5.   0.5]
 [ 4.  10. ]
 [ 3.   2. ]]


- Order of the matrices must be the same
- Add corresponding elements together
- Matrix addition is commutative (A + B = B + A)
- Matrix addition is associative (A + ( B + C ) = ( A + B ) + C)

### 2. Scalar Multiplication

In [9]:
# Multiply/divide by a scalar
print(3*A)
print(A/4)

[[ 3  0]
 [ 6 15]
 [ 9  3]]
[[0.25 0.  ]
 [0.5  1.25]
 [0.75 0.25]]


### 3. Matrix Multiplication

Am×n × Bn×p = Cm×p

- The number of columns in the first matrix must be equal to the number of rows in the second matrix. That is, the inner dimensions must be the same.
- The order of the product is the number of rows in the first matrix by the number of columns in the second matrix. That is, the dimensions of the product are the outer dimensions.
- Since the number of columns in the first matrix is equal to the number of rows in the second matrix, you can pair up entries.
- Each element in row i from the first matrix is paired up with an element in column j from the second matrix.
- The element in row i, column j, of the product is formed by multiplying these paired elements and summing them.
- Each element in the product is the sum of the products of the elements from row i of the first matrix and column j of the second matrix.
- There will be n products which are summed for each element in the product.

#### Matrix multiplication is not commutative
- Multiplication of real numbers is.
- The inner dimensions may not agree if the order of the matrices is changed.
#### Do not simply multiply corresponding elements together
- Since the order (dimensions) of the matrices don't have to be the same, there may not be corresponding elements to multiply together.
- Multiply the rows of the first by the columns of the second and add.
#### There is no matrix division
- There is no defined process for dividing a matrix by another matrix.
- A matrix may be divided by a scalar.

In [17]:
# Define two arrays
A = np.array([[1, 0  ], [2, 5], [3, 1]])
print ("Size of A:",np.shape(A))

B = np.array([[4, 0.5,2], [0, 1, 5]])
print ("Size of B:",np.shape(B))

# Multiply them together
print("A X B = \n",A.dot(B))

print("B X A =\n", B.dot(A))

Size of A: (3, 2)
Size of B: (2, 3)
A X B = 
 [[ 4.   0.5  2. ]
 [ 8.   6.  29. ]
 [12.   2.5 11. ]]
B X A =
 [[11.   4.5]
 [17.  10. ]]


### 4. Matrix Transpose and Inverse


#### 1. Transpose

In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal, that is it switches the row and column indices of the matrix by producing another matrix denoted as Aᵀ.



In [20]:
print("A  = \n",A)
print("A transpose = \n",np.transpose(A))

A  = 
 [[1 0]
 [2 5]
 [3 1]]
A transpose = 
 [[1 2 3]
 [0 5 1]]


#### 2. Inverse

The inverse of A is A<sup>-1 </sup>only when:

A × A<sup>-1 </sup> = A<sup>-1 </sup> × A = I

Sometimes there is no inverse at all.


In [25]:
v = np.arange(1,5 )
print ("row matrix:\n", v,np.shape(v))
A = v.reshape((2, 2))
print ("Matrix:\n", d,"\nMatrix size:",np.shape(d))
print("A  = \n",A)
print("A inverse = \n",np.linalg.inv(A))

row matrix:
 [1 2 3 4] (4,)
Matrix:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 
Matrix size: (3, 4)
A  = 
 [[1 2]
 [3 4]]
A inverse = 
 [[-2.   1. ]
 [ 1.5 -0.5]]
